apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uid-app.fullname" . }}
data:
  config.json: |-
    {
        "database": {
            "host": "{{ .Values.database.host }}",
            "port": {{ .Values.database.port }},
            "user": "{{ .Values.database.user }}",
            "password": "{{ .Values.database.password }}",
            "dbname": "{{ .Values.database.dbname }}"
        }
    }
